# Generated by Django 2.1.7 on 2020-02-12 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
        ('ads', '0001_initial'),
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Feedback', to='ads.Ad')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Feedback', to='programs.Program')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Feedback', to='stations.Station')),
            ],
        ),
    ]
