# Generated by Django 2.1.7 on 2020-06-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationtoken',
            name='key',
            field=models.CharField(max_length=250, primary_key=True, serialize=False, verbose_name='Key'),
        ),
    ]
