# Generated by Django 2.1.7 on 2020-02-13 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station_auth', '0002_auto_20200213_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stationtoken',
            old_name='statiоn',
            new_name='station',
        ),
    ]
