# Generated by Django 2.1.7 on 2020-06-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station_auth', '0002_auto_20200601_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stationtoken',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='stationtoken',
            old_name='key',
            new_name='token',
        ),
        migrations.AddField(
            model_name='stationtoken',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
