# Generated by Django 2.1.7 on 2020-01-15 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='name',
            new_name='title',
        ),
    ]
