# Generated by Django 2.1.7 on 2020-01-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_auto_20200115_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='media_type',
            field=models.CharField(choices=[('VD', 'Video media type'), ('IM', 'Image media type'), ('GF', 'GIF media type')], max_length=2, null=True),
        ),
    ]
