# Generated by Django 2.1.7 on 2020-02-29 12:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_ad_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='duration',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.9), django.core.validators.MaxValueValidator(1800)]),
        ),
    ]
