# Generated by Django 2.1.7 on 2020-03-02 14:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_auto_20200302_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='duration',
            field=models.FloatField(null=True, validators=[django.core.validators.MaxValueValidator(1800)]),
        ),
    ]
