# Generated by Django 2.1.7 on 2020-01-14 16:31

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pproviders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=60)),
                ('description', models.TextField(max_length=300)),
                ('city', models.CharField(choices=[('SO', 'Sofia city'), ('BS', 'Burgas city'), ('PL', 'Plovdiv city'), ('VA', 'Varna city')], max_length=2, null=True)),
                ('mac_addr', models.TextField(max_length=300, unique=True)),
                ('net_addr', models.TextField(max_length=300, unique=True)),
                ('p_addr', models.TextField(blank=True, max_length=300)),
                ('media_materials', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, null=True, size=None)),
                ('media_url', models.TextField(blank=True, max_length=500)),
                ('lat', models.DecimalField(decimal_places=7, max_digits=9, null=True)),
                ('long', models.DecimalField(decimal_places=7, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Station', to=settings.AUTH_USER_MODEL)),
                ('pprovider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Station', to='pproviders.PlaceProvider')),
            ],
        ),
    ]
