# Generated by Django 2.1.7 on 2020-01-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='net_addr',
            field=models.TextField(blank=True, max_length=300, unique=True),
        ),
    ]
