# Generated by Django 2.1.7 on 2020-02-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_station_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='viewers',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
