# Generated by Django 2.1.7 on 2020-01-15 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_auto_20200114_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Station', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='station',
            name='pprovider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Station', to='pproviders.Pprovider'),
        ),
    ]
