# Generated by Django 2.1.7 on 2020-01-16 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0003_auto_20200115_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='media_materials',
        ),
        migrations.RemoveField(
            model_name='station',
            name='media_url',
        ),
    ]
