# Generated by Django 2.1.7 on 2020-01-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0005_station_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='slug',
            field=models.SlugField(default='http://localhost:9123/screenbit_api/', unique=True),
        ),
    ]
