# Generated by Django 2.1.7 on 2020-01-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0006_station_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
