# Generated by Django 2.1.7 on 2020-01-17 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
        ('stations', '0009_remove_station_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Station', to='programs.Program'),
        ),
    ]
