# Generated by Django 2.1.7 on 2020-01-18 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0011_station_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='slug',
        ),
    ]
