# Generated by Django 2.1.7 on 2020-01-24 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daily_programs', '0004_dailyprogram_time_shema'),
        ('stations', '0012_remove_station_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='program',
        ),
        migrations.AddField(
            model_name='station',
            name='daily_program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Station', to='daily_programs.DailyProgram'),
        ),
    ]
