# Generated by Django 2.1.7 on 2020-01-23 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_programs', '0002_auto_20200123_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyprogram',
            old_name='program_members',
            new_name='program_member',
        ),
    ]
