# Generated by Django 2.1.7 on 2020-01-23 15:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_programs', '0003_auto_20200123_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyprogram',
            name='time_shema',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
