# Generated by Django 2.1.7 on 2020-01-24 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_programs', '0004_dailyprogram_time_shema'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyprogram',
            old_name='program_member',
            new_name='program_members',
        ),
    ]
