# Generated by Django 2.1.7 on 2020-01-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_programs', '0005_auto_20200124_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyprogrammembership',
            name='program_index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
