# Generated by Django 2.1.7 on 2020-01-28 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daily_programs', '0006_dailyprogrammembership_program_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyprogram',
            name='time_shema',
        ),
        migrations.RemoveField(
            model_name='dailyprogrammembership',
            name='program_index',
        ),
        migrations.AlterField(
            model_name='dailyprogrammembership',
            name='daily_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dailyprmembership', to='daily_programs.DailyProgram'),
        ),
        migrations.AlterField(
            model_name='dailyprogrammembership',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dailyprmembership', to='programs.Program'),
        ),
    ]
