# Generated by Django 2.1.7 on 2020-01-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_programs', '0007_auto_20200128_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyprogram',
            name='is_in_use',
            field=models.BooleanField(default=False),
        ),
    ]
