# Generated by Django 2.1.7 on 2020-01-19 14:37

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='media_urls',
        ),
        migrations.AddField(
            model_name='program',
            name='media_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
