# Generated by Django 2.1.7 on 2020-01-19 16:06

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_auto_20200119_1606'),
        ('programs', '0003_auto_20200119_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='ads',
            field=models.ManyToManyField(to='ads.Ad'),
        ),
        migrations.AlterField(
            model_name='program',
            name='media_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True),
        ),
    ]
