# Generated by Django 2.1.7 on 2020-01-19 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_auto_20200119_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='ad_ids',
        ),
    ]
