# Generated by Django 2.1.7 on 2020-01-24 13:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_auto_20200119_1606'),
        ('programs', '0006_remove_program_media_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramAdMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_index', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.Ad')),
            ],
        ),
        migrations.RemoveField(
            model_name='program',
            name='ads',
        ),
        migrations.AddField(
            model_name='program',
            name='ad_order_schema',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='programadmembership',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.Program'),
        ),
        migrations.AddField(
            model_name='program',
            name='ad_members',
            field=models.ManyToManyField(through='programs.ProgramAdMembership', to='ads.Ad'),
        ),
    ]
