# Generated by Django 2.1.7 on 2020-01-28 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0007_auto_20200124_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='ad_order_schema',
        ),
        migrations.RemoveField(
            model_name='programadmembership',
            name='ad_index',
        ),
        migrations.AlterField(
            model_name='programadmembership',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pradmembership', to='ads.Ad'),
        ),
        migrations.AlterField(
            model_name='programadmembership',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pradmembership', to='programs.Program'),
        ),
    ]
