# Generated by Django 2.1.7 on 2020-01-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0008_auto_20200128_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='programadmembership',
            name='ad_index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
