# Generated by Django 2.1.7 on 2020-02-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screenbit_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='files/%Y/%m/%d'),
        ),
    ]
