# Generated by Django 2.1.7 on 2020-01-14 16:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_auto_20200114_1642'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pproviders', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlaceProvider',
            new_name='Pprovider',
        ),
    ]
