# Generated by Django 2.1.7 on 2020-01-15 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pproviders', '0003_auto_20200114_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pprovider',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pprovider', to=settings.AUTH_USER_MODEL),
        ),
    ]
